package enum_;

public enum enum_genere {
	FANTASY, AVVENTURA, ROMANTICO, CONTEMPORANEO, MISTERO, HORROR, THRILLER, PRANORMALE, STORICO, SCIENZA, BAMBINI,
	CRESCITAPERSONALE, MOTIVAZIONALE, VIAGGI, DIVERTENTI
}
